import { Link, useNavigate, useParams } from "@tanstack/react-router";
import { ArrowLeft, Pause, Play, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { PageHeader } from "@/components/gitbrief/shared/page-header";
import {
  ErrorState,
  extractErrorMessage,
} from "@/components/gitbrief/shared/error-state";
import { SkeletonList } from "@/components/gitbrief/shared/skeleton-list";
import { ScheduleForm } from "@/components/gitbrief/schedules/schedule-form";
import {
  useDeleteBriefSchedule,
  useGetBriefSchedule,
  usePauseBriefSchedule,
  useResumeBriefSchedule,
} from "@/hooks/api/use-brief-schedules";

export function ScheduleDetailPage() {
  const params = useParams({ from: "/schedules/$scheduleId" as never }) as {
    scheduleId: string;
  };
  const navigate = useNavigate();

  const scheduleQuery = useGetBriefSchedule(params.scheduleId);
  const pauseMutation = usePauseBriefSchedule();
  const resumeMutation = useResumeBriefSchedule();
  const deleteMutation = useDeleteBriefSchedule();

  const [confirmDeleteOpen, setConfirmDeleteOpen] = useState(false);

  if (scheduleQuery.isLoading) {
    return (
      <>
        <PageHeader title="…" />
        <SkeletonList rows={6} rowHeight={36} />
      </>
    );
  }
  if (scheduleQuery.isError || !scheduleQuery.data?.data) {
    return (
      <>
        <PageHeader title="Schedule" />
        <ErrorState
          message={extractErrorMessage(scheduleQuery.error)}
          onRetry={() => scheduleQuery.refetch()}
        />
      </>
    );
  }

  const schedule = scheduleQuery.data.data;

  const handleToggle = async () => {
    try {
      if (schedule.paused) {
        await resumeMutation.mutateAsync(schedule.id);
        toast.success("Schedule resumed");
      } else {
        await pauseMutation.mutateAsync(schedule.id);
        toast.success("Schedule paused");
      }
    } catch (err) {
      toast.error(extractErrorMessage(err));
    }
  };

  const handleDelete = async () => {
    try {
      await deleteMutation.mutateAsync(schedule.id);
      toast.success("Schedule deleted");
      await navigate({ to: "/schedules" });
    } catch (err) {
      toast.error(extractErrorMessage(err));
    }
  };

  return (
    <>
      <div className="mb-3">
        <Link
          to="/schedules"
          className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-3" /> Back to schedules
        </Link>
      </div>

      <PageHeader
        title={schedule.name}
        description={schedule.paused ? "Paused" : "Active"}
        actions={
          <>
            <Button size="sm" variant="outline" onClick={handleToggle}>
              {schedule.paused ? (
                <>
                  <Play className="size-3.5" /> Resume
                </>
              ) : (
                <>
                  <Pause className="size-3.5" /> Pause
                </>
              )}
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="text-destructive hover:text-destructive"
              onClick={() => setConfirmDeleteOpen(true)}
            >
              <Trash2 className="size-3.5" /> Delete
            </Button>
          </>
        }
      />

      <ScheduleForm existing={schedule} />

      <AlertDialog open={confirmDeleteOpen} onOpenChange={setConfirmDeleteOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete this schedule?</AlertDialogTitle>
            <AlertDialogDescription>
              Briefs already generated by this schedule stay. Future runs stop.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={handleDelete} disabled={deleteMutation.isPending}>
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
